sudo: false

language: generic

script: /bin/true

jobs:
  include:
    - script: echo "Build"
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "Not part of build stage"

    - stage: "Deploy"
      script: echo "Deploy 1"
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "Should fail"; false
    - stage: "Deploy"
      script: echo "Deploy 2"
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "Should pass"; true
