sudo: false

language: generic

script: /bin/true

jobs:
  include:
    - stage: Deploy 1
      script: echo "Deploy 1"
      deploy:
      - provider: script
        script: /bin/false
    - stage: Deploy 2
      script: echo "Deploy 2"
      deploy:
      - provider: script
        script: /bin/true
